spring:
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-oauth-secret.yml
      - classpath:application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework:
        security:
          web: trace
